# Generated by Django 5.2.13 on 2026-05-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='media_platform',
            field=models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('twitter', 'Twitter / X'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('other', 'Autre')], max_length=20, verbose_name='Plateforme'),
        ),
        migrations.AddField(
            model_name='article',
            name='media_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL du média externe'),
        ),
    ]
