# Generated by Django 5.2.13 on 2026-05-11 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_article_media_platform_article_media_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_enabled',
            field=models.BooleanField(default=False, verbose_name="Activer l'envoi SMTP"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_from_email',
            field=models.EmailField(blank=True, default='newsletter@capturemedia.tg', max_length=254, verbose_name='Email expéditeur'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', max_length=200, verbose_name='Serveur SMTP'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mot de passe SMTP'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587, verbose_name='Port SMTP'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, verbose_name='Utiliser TLS'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=200, verbose_name="Nom d'utilisateur SMTP"),
        ),
        migrations.CreateModel(
            name='NewsletterSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300, verbose_name='Sujet')),
                ('body_html', models.TextField(verbose_name='Contenu HTML')),
                ('recipients_count', models.PositiveIntegerField(default=0, verbose_name='Destinataires')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Envoyés')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Échoués')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Envoi newsletter',
                'verbose_name_plural': 'Envois newsletter',
                'ordering': ['-sent_at'],
            },
        ),
    ]
