# Generated by Django 5.2.13 on 2026-05-30 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_sitesettings_smtp_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='donations/campaigns/', verbose_name='Image de couverture')),
                ('goal_amount', models.PositiveIntegerField(default=0, verbose_name='Objectif (FCFA)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Se termine le')),
            ],
            options={
                'verbose_name': 'Campagne de dons',
                'verbose_name_plural': 'Campagnes de dons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom du canal')),
                ('channel_type', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank', 'Virement bancaire'), ('paypal', 'PayPal'), ('card', 'Carte bancaire'), ('other', 'Autre')], default='mobile_money', max_length=20, verbose_name='Type')),
                ('account_number', models.CharField(blank=True, max_length=120, verbose_name='Numéro / IBAN / identifiant')),
                ('account_name', models.CharField(blank=True, max_length=120, verbose_name='Intitulé du compte')),
                ('ussd_code', models.CharField(blank=True, max_length=40, verbose_name='Code USSD (ex : *155#)')),
                ('instructions', models.TextField(blank=True, verbose_name='Instructions')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='donations/channels/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Canal de don',
                'verbose_name_plural': 'Canaux de don',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='donation_headline',
            field=models.CharField(blank=True, default='Le média du peuple, soutenu par le peuple', max_length=200, verbose_name='Titre de la page de dons'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='donation_message',
            field=models.TextField(blank=True, default='Capture Media informe librement et gratuitement le peuple togolais. Votre soutien, même modeste, garantit notre indépendance et notre liberté de ton.', verbose_name="Message d'appel aux dons"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='donations_enabled',
            field=models.BooleanField(default=True, verbose_name='Activer la page de dons'),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(choices=[('financial', 'Financier'), ('material', 'Matériel')], default='financial', max_length=20, verbose_name='Type de don')),
                ('donor_name', models.CharField(max_length=120, verbose_name='Nom du donateur')),
                ('donor_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('donor_phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Don anonyme')),
                ('amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Montant (FCFA)')),
                ('currency', models.CharField(default='FCFA', max_length=10, verbose_name='Devise')),
                ('transaction_reference', models.CharField(blank=True, max_length=120, verbose_name='Référence transaction')),
                ('item_description', models.TextField(blank=True, verbose_name='Description du matériel')),
                ('estimated_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='Valeur estimée (FCFA)')),
                ('message', models.TextField(blank=True, verbose_name='Mot de soutien')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('rejected', 'Rejeté')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Reçu le')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmé le')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='backend.donationcampaign', verbose_name='Campagne')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='backend.donationchannel', verbose_name='Canal utilisé')),
            ],
            options={
                'verbose_name': 'Don',
                'verbose_name_plural': 'Dons',
                'ordering': ['-created_at'],
            },
        ),
    ]
